
version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  gps-tracker:
    image: xcenax/gps-tracker:latest
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  eta-calculator:
    image: xcenax/eta-calculator:latest
    ports:
      - "8001:8000"
    depends_on:
      - kafka

  notifier:
    image: xcenax/notifier:latest
    ports:
      - "8002:8000"
    depends_on:
      - kafka
